#!/usr/bin/env python3
"""Render slop-cut signals + original/cleaned text into a before/after diff
card. Self-contained HTML, no CDN. Deterministic.
"""
import argparse
import json

CAT_COLORS = {
    "rhythm": "#58a6ff", "structure": "#bc8cff", "vocabulary": "#f778ba",
    "hedging": "#f0883e", "punctuation": "#56d364",
}


def esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;"))


def main():
    ap = argparse.ArgumentParser(prog="report.py")
    ap.add_argument("signals")
    ap.add_argument("--original", required=True)
    ap.add_argument("--cleaned", default="")
    ap.add_argument("--out", default="slop-report.html")
    ap.add_argument("--title", default="Slop Index report")
    args = ap.parse_args()

    d = json.load(open(args.signals))
    original = open(args.original, errors="ignore").read()
    cleaned = open(args.cleaned).read() if args.cleaned else ""

    idx = d["slop_index"]
    bar = min(idx, 100)
    color = "#56d364" if idx < 25 else "#f5c542" if idx < 50 else "#f0883e" if idx < 75 else "#ff5d5d"

    sig_rows = ""
    for s in d["signals"]:
        sig_rows += (f'<li><span class="dot" style="background:'
                     f'{CAT_COLORS[s["category"]]}"></span>'
                     f'<b>{esc(s["id"])}</b> '
                     f'<span class="str">{s["strength"]}</span> '
                     f'<span class="cat">{s["category"]}</span><br>'
                     f'<span class="snip">{esc(s["snippet"])}</span></li>')

    contrib_rows = "".join(
        f'<div class="bar"><span style="width:{min(v,100)}%;'
        f'background:{CAT_COLORS[k]}"></span></div>'
        f'<div class="blabel">{k} {v:.1f}</div>'
        for k, v in d["contributions"].items())

    diff = ""
    if cleaned:
        diff = (f'<div class="cols"><div><h3>Before (idx {idx})</h3>'
                f'<pre>{esc(original)}</pre></div>'
                f'<div><h3>After cut</h3><pre>{esc(cleaned)}</pre></div></div>')

    html = f"""<!doctype html><html><head><meta charset="utf-8">
<title>{esc(args.title)}</title><style>
body{{background:#0d1117;color:#e6edf3;font:15px/1.5 -apple-system,system-ui,sans-serif;margin:0;padding:32px}}
h1{{margin:0 0 4px}} .sub{{color:#8b949e;margin-bottom:20px}}
.score{{font:700 64px/1 monospace;color:{color};margin:8px 0 4px}}
.scorebox{{background:#161b22;border:1px solid #30363d;border-radius:12px;padding:20px;display:inline-block;margin-bottom:20px}}
.bar{{height:10px;background:#21262d;border-radius:5px;overflow:hidden;margin:4px 0}}
.bar span{{display:block;height:100%}} .blabel{{font-size:12px;color:#8b949e;margin-bottom:8px}}
h2{{border-top:1px solid #30363d;padding-top:14px;margin-top:20px;font-size:16px}}
ul{{list-style:none;padding:0;margin:8px 0}} li{{margin:8px 0}}
.dot{{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:6px}}
.str{{color:#f0883e;font-weight:700}} .cat{{color:#8b949e;font-size:12px;margin-left:6px}}
.snip{{color:#c9d1d9;font-size:13px;display:block;margin:2px 0 0 15px}}
.cols{{display:flex;gap:16px}} .cols>div{{flex:1}} pre{{white-space:pre-wrap;background:#161b22;border:1px solid #30363d;border-radius:8px;padding:12px;max-height:340px;overflow:auto}}
footer{{color:#6e7681;font-size:12px;margin-top:28px}}
</style></head><body>
<h1>{esc(args.title)}</h1>
<div class="sub">higher index = more AI-sounding; em-dash weighted weakly by design</div>
<div class="scorebox"><div class="score">{idx}</div>
<div>Slop Index / 100</div></div>
<h2>Contribution by category (max 100)</h2>{contrib_rows}
<h2>Signals</h2><ul>{sig_rows}</ul>
{diff}
<footer>generated by slop-cut &middot; deterministic signals in scan.py</footer>
</body></html>"""
    open(args.out, "w").write(html)
    print(f"slop_index={idx} signals={len(d['signals'])}")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
